---
title: "análisis principal"
subtitle: "Clustering implementation and groups comparisons"
# format: html
# execute:
#   echo: true
#   warning: false
#   message: false
# toc: true
# date: "`r Sys.time()`"
# css: style.css
---

## 0. Packages, functions and data

```{r libraries and functions, message= F}

rm(list = ls())
unlink("Tables/*")
unlink("Figures/*")

# set.seed(123)
library(tidyverse)
library(flextable)
library(ggpubr)
source("helper/helper_tables.R")
source("helper/helper_functions.R")

```

```{r data loading, message= F}

df_completo = read.csv("data/df_completo_impredecibilidad_adolescencia_carrera.csv")

orientacion_vocacional_cuanti_raw <- read.csv("data/data_raw/orientacion_vocacional_cuanti_raw.csv")
orientacion_vocacional_items <- read.csv("data/data_raw/orientacion_vocacional_cuanti_items.csv") %>% 
  distinct()

```


## 1. Tabla 1. Probabilidad de continuar con los estudios superiores

```{r Probabilidad continuar tabla}

variables = c("probable_continuar_estudios")

orientacion_vocacional_cuanti_raw %>% 
  filter(item_name %in% variables) %>% 
  # group_by(item_name, response) %>% 
  summarise(Cantidad = n(),.by = c(item_name, response),
            Porcentaje = paste(round((Cantidad/nrow(df_completo))*100, digits = 1), "%")
            ) %>% 
  arrange(response) %>% 
  pivot_wider(
    id_cols = item_name,
    names_from = response,
    values_from = Porcentaje
  ) %>% 
  mutate(item_name = "¿Cuán probable es que continúes los estudios superiores al terminar la secundaria?") %>% 
  custom_flextable("Tabla 1. Probabilidad de continuar la secundaria para toda la muestra")
 


```


```{r Probabilidad continuar figura}

variables = c("probable_continuar_estudios")

orientacion_vocacional_cuanti_raw %>% 
  filter(item_name %in% variables) %>% 
  # group_by(item_name, response) %>% 
  summarise(Cantidad = n(),.by = c(item_name, response),
            Porcentaje = round((Cantidad/nrow(df_completo))*100, digits = 1)
            ) %>% 
  ggplot(aes(x = response, y = Porcentaje))+
  geom_bar(stat = "identity")+
  scale_x_continuous(limits = c(0.5,10.5), breaks = 1:10)+
  ggtitle("¿Cuán probable es que continúes los estudios superiores al terminar la secundaria?")
 


```



```{r sample info}


df_completo %>% 
  group_by(gender) %>% 
  summarise(Participantes = as.character(n()),
            Probabilidad = mean_sd(probable_continuar_estudios)
            ) %>% 
  # mutate(Probabilidad = ifelse(Participantes == 1, "-", Probabilidad)) %>% 
  select(-Participantes) %>% 
  pivot_longer(
    cols = c(Probabilidad), 
    names_to = " ", 
    values_to = "valor"
  ) %>% 
  pivot_wider(
    names_from = gender, 
    values_from = valor
  ) %>% 
  # mutate(Total = c(
  #   as.character(nrow(df_completo)),
  #   mean_sd(df_completo$age_years)
  # )) %>% 
  # select(" ", Total, everything()) %>% 
  # flextable() %>% 
  custom_flextable("Tabla 1. Probabilidad de continuar los estudios (del 1 al 10)")
 


```



```{r sample info}




df_completo %>% 
  filter(gender %in% c("Femenino", "Masculino")) %>% 
  # group_by(gender, probable_continuar_estudios) %>% 
  summarise(Cantidad = n(),.by = c(gender, probable_continuar_estudios)
            ) %>% 
  group_by(gender) %>% 
  mutate(Porcentaje = Cantidad/sum(Cantidad)*100) %>% 
  ggplot(aes(x = probable_continuar_estudios, y = Porcentaje, fill = gender))+
  geom_bar(stat = "identity", position = "dodge")+
  scale_x_continuous(limits = c(0.5,10.5), breaks = 1:10)+
  ggtitle("¿Cuán probable es que continúes los estudios superiores al terminar la secundaria?\nPor género")
 


```


```{r sample info}


probable_continuar_x_educ_mother <- df_completo %>% 
  group_by(max_educ_level_mother_agrup) %>% 
  summarise(Participantes = as.character(n()),
            'De acuerdo al nivel educativo de la madre' = mean_sd(probable_continuar_estudios)
            ) %>% 
  select(-Participantes) %>% 
  pivot_longer(
    cols = c('De acuerdo al nivel educativo de la madre'), 
    names_to = " ", 
    values_to = "valor"
  ) %>% 
  pivot_wider(
    names_from = max_educ_level_mother_agrup, 
    values_from = valor
  )

probable_continuar_x_educ_father <- df_completo %>% 
  group_by(max_educ_level_father_agrup) %>% 
  summarise(Participantes = as.character(n()),
            'De acuerdo al nivel educativo de la madre' = mean_sd(probable_continuar_estudios)
            ) %>% 
  select(-Participantes) %>% 
  pivot_longer(
    cols = c('De acuerdo al nivel educativo de la madre'), 
    names_to = " ", 
    values_to = "valor"
  ) %>% 
  pivot_wider(
    names_from = max_educ_level_father_agrup, 
    values_from = valor
  )



rbind(probable_continuar_x_educ_mother, probable_continuar_x_educ_father)%>% 

  custom_flextable("Tabla 1. Probabilidad de continuar los estudios de acuerdo al nivel educativo de los padres")
 


```



```{r fig.width = 10}

p_1 <- df_completo %>% 

  ggplot(aes(x = max_educ_level_mother_agrup, y = probable_continuar_estudios, fill = gender))+
  geom_boxplot()+
  # coord_flip()+
  ggtitle("Probabilidad de continuar los estudios según el nivel educativo de la madre")+
  theme_minimal()+
  theme(axis.title.x = element_blank())

p_2 <- df_completo %>% 

  ggplot(aes(x = max_educ_level_mother_agrup, y = probable_continuar_estudios, fill = gender))+
  geom_boxplot()+
  # coord_flip()+
  ggtitle("Probabilidad de continuar los estudios según el nivel educativo del padre")+
  theme_minimal()+
  theme(axis.title.x = element_blank())



ggpubr::ggarrange(p_1, p_2,ncol = 1,  common.legend = T, legend = "bottom")

# table(df_completo$max_educ_level_father_agrup)


```


## 1. Tabla 1. Considera trabajar

```{r Probabilidad continuar tabla}

variables = c("considera_trabajar")

orientacion_vocacional_cuanti_raw %>% 
  filter(item_name %in% variables) %>% 
  mutate(response = ifelse(response == 0, "No", "Si")) %>% 
  # group_by(item_name, response) %>% 
  summarise(Cantidad = n(),.by = c(item_name, response),
            Porcentaje = paste(round((Cantidad/nrow(df_completo))*100, digits = 1), "%")
            ) %>% 
  arrange(response) %>% 
  pivot_wider(
    id_cols = item_name,
    names_from = response,
    values_from = Porcentaje
  ) %>% 
  mutate(item_name = "¿Considerás necesario trabajar inmediatamente al egresar?") %>% 
  custom_flextable("")
 


```




## 1. Tabla 1. Considera trabajar

```{r Probabilidad continuar tabla}

df_completo %>% 
  group_by(gender) %>% 
  summarise(Participantes = as.character(n()),
            Probabilidad = mean(considera_trabajar)*100
            ) %>% 
  select(-Participantes) %>% 
  pivot_longer(
    cols = c(Probabilidad), 
    names_to = " ", 
    values_to = "valor"
  ) %>% 
  pivot_wider(
    names_from = gender, 
    values_from = valor
  ) %>% 
  custom_flextable("¿Considerás necesario trabajar inmediatamente al egresar? (%)")


```

```{r}

p_3 <- df_completo %>% 
  
  filter(gender %in% c("Femenino", "Masculino")) %>% 
  summarise(Participantes = as.character(n()),
            Porcentaje = mean(considera_trabajar)*100,
            .by = c(gender, max_educ_level_father_agrup)
            ) %>% 
  ggplot(aes(x = max_educ_level_father_agrup, y = Porcentaje, fill = gender))+
  geom_col(position = "dodge")+
    geom_text(aes(label = paste(round(Porcentaje, digits = 2), "%")), 
            position = position_dodge(width = 0.9),
            vjust = 2,
            color = "white")+
  ggtitle("Porcentaje que planea trabajar según nivel educativo del padre")+
  scale_y_continuous(limits = c(0,100))+
  theme_minimal()+
  theme(axis.title.x = element_blank())







p_4 <- df_completo %>% 
  
  filter(gender %in% c("Femenino", "Masculino")) %>% 
  summarise(Participantes = as.character(n()),
            Porcentaje = mean(considera_trabajar)*100,
            .by = c(gender, max_educ_level_mother_agrup)
            ) %>% 
  ggplot(aes(x = max_educ_level_mother_agrup, y = Porcentaje, fill = gender))+
  geom_col(position = "dodge")+
  geom_text(aes(label = paste(round(Porcentaje, digits = 2), "%")), 
            position = position_dodge(width = 0.9),
            vjust = 2,
            color = "white")+
  ggtitle("Porcentaje que planea trabajar según nivel educativo de la madre")+
  scale_y_continuous(limits = c(0,100))+
  theme_minimal()+
  theme(axis.title.x = element_blank())




ggpubr::ggarrange(p_3, p_4,ncol = 1,  common.legend = T, legend = "bottom")

```



```{r}

df_completo %>% 
  ggplot(aes(x = society_ladder, y = probable_continuar_estudios,color = gender))+
  geom_point(size = 3)+
  geom_smooth(method = "lm")


df_completo %>% 
  ggplot(aes(x = unpred_future_general, y = probable_continuar_estudios, color = gender))+
  geom_point(size = 3)+
  geom_smooth(method = "lm")


df_completo %>% 
  ggplot(aes(x = unpred_future_economy, y = probable_continuar_estudios, color = gender))+
  geom_point(size = 3)+
  geom_smooth(method = "lm")

df_completo %>% 
  ggplot(aes(x = unpred_life_1_year, y = probable_continuar_estudios, color = gender))+
  geom_point(size = 3)+
  geom_smooth(method = "lm")



df_completo %>% 
  ggplot(aes(x = gender, y = CIP_01_decision, fill = gender))+
  geom_boxplot()
  geom_smooth(method = "lm")
  
  
  
df_completo %>% 
  ggplot(aes(x = unpred_future_general, y = CIP_01_decision, color = gender))+
  geom_point(size = 3)+
  geom_smooth(method = "lm")



```

